# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- category
- tagcloud
- archive
- links
thumbnail: true

# Contacts
contacts:
  github: http://github.com/getwe
  weibo: http://weibo.com/2310325
  #twitter: '#'
  #facebook: '#'
  #dribbble: '#'
  rss: /atom.xml

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
